### PR TITLE
Updated environment expansion for TDVP

### PR DESCRIPTION
**Pull request by jesse-osborne**

### CODE REVIEW

**Comment by jesse-osborne** [comment]
TODO:
- The new functions to do the environment expansion (`ExpandLeftEnvironment` and `ExpandRightEnvironment` in mp-algorithms/tdvp.cpp) should probably be placed somewhere better. Ideally, the DMRG and TDVP tools could use the same function(?)
- The way the environement expansion works in mp-itdvp has to be completely refactored to be written in terms of these functions. It probably needed to be rewritten anyway though.
- There may be cases where some of the middle elements of the expansion tensor (w.r.t. the MPO index) product spurious states (I think I had to do something convoluted like $\sum_i S^x_i S^x_{i+1} (I_{i+2} + 10^{-6} S^x_{i+2})$ to get this sort of thing to happen). I should reinvestigate this to see if this can cause serious problems.
- Is it worth keeping the old expansion method as an option? This is since the new method will produce different results for the same parameter, so old script won't produce the same results. But then you could just compile and older version of the tool to run these scripts.

**Comment by jesse-osborne** [comment]
The iTDVP code has been refactored to use the new environment expansion functions.

However, the iTDVP code is numerically unstable when the eigenvalue cutoff (`-d`) is too small. I can't get this to happen with the old iTDVP code and the new TDVP code. This probably has to do with the way the bonds are expanded before evolving the unit cell.

**Comment by jesse-osborne** [comment]
This is probably ready to merge now. I've also commented out a bunch of the debug trace lines in the triangular MPO solver and GMRES code, which I assume is okay?

**Comment by jesse-osborne** [comment]
The only outstanding issue is where to place the `ExpandLeftEnvironment` and `ExpandRightEnvironment` functions, but perhaps it makes sense to handle that later with the DMRG expansion code?

**Comment by ianmccul** [comment]
yeah the location of the Expand{L|R}Environment can be handled later.

I agree, if you are happy that the new code is better than the old code to the extent that there is no recommended use for the old code, then there is no reason to keep it around.  If you want to do some benchmarking you can, as you suggest, just use the old code.  Maybe it is worth tagging the old version so you can find it easier.

**Pull request merged**
